#Array 3D

If a 1D array is just a regular array, and a 2D array is an array of arrays, then a 3D array is an array of arrays of arrays. Every additional dimension just gets you more deeply nested arrays. 

In [1]:
import numpy as np

In [2]:
arr1_2d = np.array([[1, 2], [3,4]])
arr2_2d = np.array([[5, 6], [7, 8]])
arr3_2d = np.array([[9, 2], [3, 4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])

In [3]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [10]:
arr1 = np.array([arr_3d, arr_3d])
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 9, 2,
       3, 4])

In [8]:
arr = np.zeros((3,4,2))
arr.shape

(3, 4, 2)

In [9]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr_3d.reshape((4,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])