#Array 3D

If a 1D array is just a regular array, and a 2D array is an array of arrays, then a 3D array is an array of arrays of arrays. Every additional dimension just gets you more deeply nested arrays. 

In [1]:
import numpy as np

In [2]:
arr1_2d = np.array([[1, 2], [3,4]])
arr2_2d = np.array([[5, 6], [7, 8]])
arr3_2d = np.array([[9, 2], [3, 4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])

In [3]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [10]:
arr1 = np.array([arr_3d, arr_3d])
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 9, 2,
       3, 4])

In [8]:
arr = np.zeros((3,4,2))
arr.shape

(3, 4, 2)

In [9]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr_3d.reshape((4,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

#Atividade 1:

##Reduza o array (5,7) a apenas uma dimensão

In [18]:
a57 = np.random.random((5,7))
a57 = a57.flatten()
a57

array([0.50301587, 0.30807473, 0.77348698, 0.10235967, 0.12349604,
       0.01132796, 0.76911425, 0.37024206, 0.59601964, 0.95103542,
       0.81967488, 0.87094076, 0.07886689, 0.79187719, 0.27269464,
       0.84361207, 0.50000741, 0.76124294, 0.49924619, 0.18957942,
       0.53025914, 0.12274273, 0.90913981, 0.06051948, 0.88334266,
       0.30002698, 0.67345343, 0.46441198, 0.29992549, 0.83475184,
       0.75548447, 0.78526243, 0.30603642, 0.7941573 , 0.36726273])

#Atividade 2:

##Considerando que você é uma organizadora de um jogo de bingo.Crie um array que irá representar a cartilha desses jogos de bingo. Os números das suas cartelas variam entre 1 e 30 e você terá 10 participantes. Cada cartela terá 12 números (4,3). Crie um array que represente esse jogo.

In [20]:
bingo = np.random.randint(1, 31,size= (10,4,3))
bingo

array([[[12, 22, 24],
        [14,  6, 26],
        [19, 21, 22],
        [17,  2, 14]],

       [[ 4,  1, 22],
        [15, 18, 28],
        [10, 21,  4],
        [24, 19,  7]],

       [[17,  3, 26],
        [25, 13,  6],
        [15, 19, 18],
        [25,  6, 12]],

       [[15, 25, 28],
        [30, 16,  9],
        [ 7, 18,  6],
        [ 7,  7,  9]],

       [[13, 15, 21],
        [25,  5, 11],
        [23, 17,  1],
        [ 7,  8, 23]],

       [[16, 29, 20],
        [ 1,  4, 23],
        [21, 29, 26],
        [28, 10,  3]],

       [[27, 10, 27],
        [28,  9, 12],
        [14, 29, 13],
        [ 8,  1, 13]],

       [[25, 30,  3],
        [19, 29,  1],
        [10, 17, 10],
        [ 5, 16,  2]],

       [[11, 28, 14],
        [25, 14, 16],
        [17, 20,  3],
        [18, 14,  5]],

       [[22, 19, 17],
        [ 6, 12, 23],
        [22,  6, 27],
        [ 9, 21, 17]]])

#Atividade 3?

##Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [23]:
bingo.reshape((5,4,6))
bingo

array([[[23, 18, 28,  3, 18, 21],
        [ 3, 23, 10, 20,  4, 18],
        [ 6, 25,  8, 22, 10, 26],
        [29, 28, 21, 23,  1, 27]],

       [[11, 27, 25, 24, 15, 18],
        [ 3,  6, 18,  6, 20, 22],
        [19, 30, 18,  7, 10, 29],
        [14, 22,  5,  6, 23, 22]],

       [[21,  8, 17,  9, 16, 28],
        [25, 16,  4,  7, 12, 11],
        [ 8,  9, 28, 16, 17, 24],
        [15,  4, 30, 18, 15, 22]],

       [[27, 11, 16,  5, 24, 17],
        [19, 19,  1, 29, 28,  4],
        [22, 29, 28,  1, 20, 28],
        [ 6, 11, 24, 20,  5,  1]],

       [[28,  2,  8,  5, 22, 13],
        [23,  5, 16, 20,  9,  3],
        [25, 28, 16,  6, 10,  7],
        [ 9, 16, 17,  3, 18, 18]]])