In [9]:
import numpy as np 

In [10]:
#Criando lista
l = [1,2,3,4,5,6,7,8,9,10]

#Inserindo no array
arr1 = np.array(l)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#Criação de array utilizando tuplas
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
#Criação de array utilizando range
arr_range = np.arange(1,11)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.random.random((3,3))

array([[0.2563944 , 0.04258463, 0.33481585],
       [0.76594998, 0.06876397, 0.65148986],
       [0.87330575, 0.01790487, 0.73823837]])

#Atividade 1:

Crie um array com 4 Linhas e 3 colunas com valores aleatórios.

In [14]:
np.random.random((4,3))

array([[0.95191879, 0.06049519, 0.62781548],
       [0.27826696, 0.09871339, 0.24173388],
       [0.68825327, 0.73111616, 0.62683486],
       [0.5857103 , 0.96220735, 0.99852079]])

#Atividade 2:

Crie um array com 5 colunas e 10 linhas inicializados com zeros.

In [15]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#Atividade 3: 

Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatórios.

In [17]:
np.random.randint(30, size=(3,5))

array([[16,  8, 22, 23, 25],
       [15, 22, 23,  5, 21],
       [15, 18, 21, 20, 12]])