#Tipo de dados em um numpy array

In [4]:
import numpy as np 

In [3]:
np.array([5.4, 6.7, 2.1]).dtype
np.array([5, 6, 2]).dtype

dtype('int32')

In [4]:
np.array(["Hello, Oi, Yolo"]).dtype

dtype('<U15')

In [7]:
#Subscreve os inteiros por float
x = np.array([3,4,2.1])

In [8]:
#Transforma int em float
x[0]

3.0

In [9]:
np.array([True,3,False]).dtype

dtype('int32')

In [10]:
#Converteu de float para int
x.astype(np.int32)

array([3, 4, 2])

##Manipulando array



In [5]:
arr = np.array([2,4,6,7,8])
arr[1]

4

In [6]:
cartela_bing = np.array([[2,4,6,7,8],[1,3,5,7,9],[10,20,30,40,50],[11,22,33,44,55]])
cartela_bing

array([[ 2,  4,  6,  7,  8],
       [ 1,  3,  5,  7,  9],
       [10, 20, 30, 40, 50],
       [11, 22, 33, 44, 55]])

In [7]:
#Slice - Pega todas as linhas da segunda coluna
cartela_bing[:,1]

array([ 4,  3, 20, 22])

In [10]:
cartela_bing[:,1].reshape(4,1)

array([[ 4],
       [ 3],
       [20],
       [22]])

In [11]:
#Primeira Linhas
cartela_bing[0]

array([2, 4, 6, 7, 8])

In [12]:
#Organizou na ordem vertical
np.sort(cartela_bing)

array([[ 2,  4,  6,  7,  8],
       [ 1,  3,  5,  7,  9],
       [10, 20, 30, 40, 50],
       [11, 22, 33, 44, 55]])

In [13]:
#Organizou na ordem horizontal
np.sort(cartela_bing, axis=0)

array([[ 1,  3,  5,  7,  8],
       [ 2,  4,  6,  7,  9],
       [10, 20, 30, 40, 50],
       [11, 22, 33, 44, 55]])

#Atividade 1

Como bióloga marinha,me encontrei em uma expedição nas profundezas do Oceano Pacífico,onde estávamos estudando a biodiversidade e a saúde dos recifes de coral.O catálogo abaixo demonstra dados das espécies encontradas,considere a seguinte ordem de colunas:

**ID da espécie,quantidade de representantes encontrados,profundeza,tamanho médio da espécie.**
 
a.Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
b.De qtd_especies selecione apenas as primeiras 3 quantidades de espécies.
c.Print as 5 últimas quantidades de espécies.
d.Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.

In [15]:
especies=np.array([[747,89,33,5],[623,123,32,13],
                   [501,22,49,2],[116,101,42,10],
                   [297,56,69,22],[613,64,27,7],
                   [295,84,29,14],[692,105,72,16],
                   [229,103,35,5],[374,124,70,1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [16]:
#Resposta a
#Seleciona apenas a segunda coluna
qtd_especies = especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [17]:
#Resposta b
#De qtd_especies selecione apenas as primeiras 3 quantidades de espécies e print.
print(qtd_especies[:3])

[ 89 123  22]


In [22]:
#Resposta c
#Print as 5 ultimas quantidade de espécies 
print(qtd_especies[-5:])

[ 64  84 105 103 124]


In [25]:
#Resposta d
#Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.
np.sort(especies[:,3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

In [26]:
#Ordem decrescente
np.sort(especies[:,3])[::-1]

array([22, 16, 14, 13, 10,  7,  5,  5,  2,  1])

#Filtrando Arrays

Indexação sofisticada e máscara em array 2D

In [27]:
arr1 = np.array([1,2,3,4,5])
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

In [28]:
pessoas_id_idade = np.array([[1, 23],[2, 45],[3, 19],[4, 32]])
pessoas_id_idade

array([[ 1, 23],
       [ 2, 45],
       [ 3, 19],
       [ 4, 32]])

In [30]:
mask_maior21 = pessoas_id_idade[:,1]>21

In [31]:
pessoas_id_idade[mask_maior21]

array([[ 1, 23],
       [ 2, 45],
       [ 4, 32]])

In [32]:
np.where(mask_maior21)

(array([0, 1, 3], dtype=int64),)

In [33]:
cartela_bingo = np.array([[2,4,6,7,8],[1,3,5,7,9],
                         [10,20,30,40,50],[11,22,33,44,55]])
cartela_bingo

array([[ 2,  4,  6,  7,  8],
       [ 1,  3,  5,  7,  9],
       [10, 20, 30, 40, 50],
       [11, 22, 33, 44, 55]])

In [34]:
#Se os numeros forem divisiveis por 3, substitua por "div3"
np.where(cartela_bingo % 3 == 0,"div3", cartela_bingo)

array([['2', '4', 'div3', '7', '8'],
       ['1', 'div3', '5', '7', 'div3'],
       ['10', '20', 'div3', '40', '50'],
       ['11', '22', 'div3', '44', '55']], dtype='<U11')

In [35]:
#Se a idade for maios que 21, substitua por "Maior de 21"
np.where(pessoas_id_idade > 21, "Maior de 21", pessoas_id_idade)

array([['1', 'Maior de 21'],
       ['2', 'Maior de 21'],
       ['3', '19'],
       ['4', 'Maior de 21']], dtype='<U11')

#Atividade 2

##Ainda usando o Array de espécies marítimas.

a.Usando um index boolean crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho),esse valor corresponde ao valor 22.
b.Usando fency index faça um array que contém apenas dados da espécie com ID 297.
c.Usando np.where()faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
d.Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo”.

In [36]:
especies=np.array([[747,89,33,5],[623,123,32,13],
                   [501,22,49,2],[116,101,42,10],
                   [297,56,69,22],[613,64,27,7],
                   [295,84,29,14],[692,105,72,16],
                   [229,103,35,5],[374,124,70,1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [38]:
#Resposta a
#Usando um index boolean crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho),esse valor corresponde ao valor 22.
maior_especie = especies[especies[:,3] == 22]

In [39]:
#Resposta b
#Usando fency index faça um array que contém apenas dados da espécie com ID 297.
especie_297 = especies[especies[:,0] == 297]
especie_297

array([[297,  56,  69,  22]])

In [42]:
#Resposta c
#Usando np.where()faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
especies[np.where(especies[:,1] == 105)]

array([[692, 105,  72,  16]])

In [45]:
#Resposta d
#Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo”.
np.where(especies[:,2] > 60, "Profundo", especies[:,2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

#Adicionando e Removendo dados do array

In [46]:
cartela_bingo = np.array([[2,4,6,7,8],[1,3,5,7,9],
                         [10,20,30,40,50],[11,22,33,44,55]])
cartela_bingo

array([[ 2,  4,  6,  7,  8],
       [ 1,  3,  5,  7,  9],
       [10, 20, 30, 40, 50],
       [11, 22, 33, 44, 55]])

In [52]:
cartela_bingo1 = cartela_bingo[:3]
cartela_bingo2 = cartela_bingo[-1:]
cartela_bingo = np.concatenate((cartela_bingo1,cartela_bingo2))
cartela_bingo

array([[ 2,  4,  6,  7,  8],
       [ 1,  3,  5,  7,  9],
       [10, 20, 30, 40, 50],
       [11, 22, 33, 44, 55]])

In [53]:
sala_espera = np.array([[1, 30, 1, "Alice"],
                        [2, 45, 1, "Bob"],
                        [3, 19, 3, "Charlie"],
                        [4, 32, 3, "David"],])
sala_espera

array([['1', '30', '1', 'Alice'],
       ['2', '45', '1', 'Bob'],
       ['3', '19', '3', 'Charlie'],
       ['4', '32', '3', 'David']], dtype='<U11')

In [54]:
np.delete(sala_espera, 3, axis=0)

array([['1', '30', '1', 'Alice'],
       ['2', '45', '1', 'Bob'],
       ['3', '19', '3', 'Charlie']], dtype='<U11')

#Atividade 3

Ainda no conjunto 'especies.
a.Adicione mais 2 espécies ao array: [[204,10,40,12],[392,11,81,11]].b.Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1,0].

In [57]:
#Resposta a
#Adicione mais 2 espécies ao array: [[204,10,40,12],[392,11,81,11]]
novas_especies = np.array([[204,10,40,12],[392,11,81,11]]) 
np.concatenate((especies,novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [63]:
#Resposta b
#Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1,0].
ver = np.array([[0],[1],[0],[0],[0],[0],[1],[0],[1],[1]]).reshape(10,1)
ver
np.concatenate((especies,ver),axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])

#Vetorização

